image: docker:24.0.5

services:
  - name: docker:24.0.5-dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - build

build:
  stage: build
  script:
    - echo "Building rag_backend image..."
    - docker build -t rag_backend:latest ./rag_backend

    - echo "Building documentation_generator image..."
    - docker build -t documentation_generator:latest ./documentation_generator

    - echo "Building pac_cli image..."
    - docker build -t pac_cli:latest ./pac-cli

  tags:
    - docker-build


