# image: docker:24.0.5
 
# services:
# - docker:24.0.5-dind

image: docker:24.0.5

services:
  - name: docker:24.0.5-dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - build

build:
  stage: build
  script:
    - echo "Building rag_backend image..."
    - docker build -t rag_backend:latest ./rag_backend
    # - docker save rag_backend:latest -o rag_backend.tar

    - echo "Building documentation_generator image..."
    - docker build -t documentation_generator:latest ./documentation_generator
    # - docker save documentation_generator:latest -o documentation_generator.tar

    - echo "Building pac_cli image..."
    - docker build -t pac_cli:latest ./pac-cli
    # - docker save pac_cli:latest -o pac_cli.tar

  # artifacts:
  #   name: "docker-images-$CI_COMMIT_SHORT_SHA"
  #   paths:
  #     - rag_backend.tar
  #     - documentation_generator.tar
  #     - pac_cli.tar
  #   expire_in: 1 week

  tags:
    - docker-build

    # sudo sudo 

